stages:
  acquire_data:
    cmd: python3 acquire_data.py
    deps:
    - acquire_data.py
    outs:
    - git_actions_data/raw/spam.csv

  preprocess_data:
    cmd: python3 preprocess_data.py
    deps:
    - preprocess_data.py
    - git_actions_data/raw/spam.csv
    outs:
    - git_actions_data/preprocessed/spam_preprocessed.csv

  train_model:
    cmd: python3 train_model.py
    deps:
    - train_model.py
    - git_actions_data/preprocessed/spam_preprocessed.csv
    outs:
    - git_actions_models/spam_detector_model.pkl
    - git_actions_vectors/vectorizer.pickle
    - git_actions_data/metrics/metrics.json

  save_to_dvc:
    cmd: python3 save_to_dvc.py
    deps:
    - git_actions_data
    - git_actions_vectors
    - git_actions_models
