name: Training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: install_packages
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: pip install -r requirements.txt

      - name: get_data
        run: python3 acquire_data.py

      - name: preprocess_data
        run: python3 preprocess_data.py

      - name: train_model
        run: python3 train_model.py